name: Build APK

on:
  push:
    tags:
      - '*'
  workflow_dispatch:

jobs:
  Build_APK:
    runs-on: Ubuntu-latest
    steps:
      - name: Install build-dep
        run: |
          sudo apt install nodejs tree
          sudo npm install -g cordova
      - name: Clone repo
        run: git clone --recursive https://github.com/deadlyjack/Acode
      - name: Build
        run: |
          cd Acode
          yarn setup
          cordova platform add android
          yarn build android paid dev
          tree > tree.txt
          ls -a > ls.txt
      - name: Upload 
        uses: actions/upload-artifact@v2
        with:
          name: tree
          path: acode/tree.txt
      - name: Upload 2
        uses: actions/upload-artifact@v2
        with:
          name: ls
          path: acode/ls.txt
